#!/bin/bash

docker run --name=registry-ui \
  -d --restart=always \
  -it \
  --link=registry:registry \
  -e ENV_DOCKER_REGISTRY_HOST=registry \
  -e ENV_DOCKER_REGISTRY_PORT=5000 \
  -e ENV_REGISTRY_PROXY_FQDN=r.local \
  -e ENV_REGISTRY_PROXY_PORT=80 \
  -p 8080:80 \
  konradkleine/docker-registry-frontend:v2
